### ISSUE TITLE
restart containers message

### ISSUE THREAD

**Issue by b0a7** [nodeset-org/hyperdrive-constellation#27]
after adding a command line option to the cs validator and adjusting fallback node settings:

'The following containers must be restarted' message doesn't take into account which modules are disabled (sw is disabled)

![image](https://github.com/user-attachments/assets/de40cd4b-d26d-433d-8f9c-7a51c538c6cf)

it does actually just restart the enabled containers correctly though, so it is just the message that isn't accounting for the module being disabled

**Comment by jclapis** [comment]
Fixed in https://github.com/nodeset-org/hyperdrive/pull/178. Side note, this repo is for the CS daemon - TUI things should go in https://github.com/nodeset-org/hyperdrive.
